var ancestries = 
    [
      {
        "name" : "AELF",
        "move" : 6,
        "wounds" : 5,
        "save" : 6,
        "bravery" : 7,
        "cost" : 3,
        "keywords" : ["ORDER", "AELF"],
        "armykeywords" : ["Daughters of Khaine", "Idoneth Deepkin", "Lumineth Realm-lords", "Cities of Sigmar"],
        "rules" : []
      },
      {
        "name" : "BONESPLITTER ORRUK",
        "move" : 5,
        "wounds" : 5,
        "save" : 6,
        "bravery" : 7,
        "cost" : 3,
        "keywords" : ["DESTRUCTION", "ORRUK", "ORRUK WARCLANS", "BONESPLITTERZ"],
        "armykeywords" : [],
        "rules" : []
      },
      {
        "name" : "BULLGOR",
        "move" : 7,
        "wounds" : 8,
        "save" : 5,
        "bravery" : 7,
        "cost" : 8,
        "keywords" : ["CHAOS", "BEASTS OF CHAOS", "WARHERD", "BULLGOR"],
        "armykeywords" : [],
        "rules" : []
      },
      {
        "name" : "CHAOS DUARDIN",
        "move" : 4,
        "wounds" : 5,
        "save" : 4,
        "bravery" : 7,
        "cost" : 4,
        "keywords" : ["ORDER", "DUARDIN", "Legion of Azgorh"],
        "armykeywords" : [],
        "rules" : []
      },
      {
        "name" : "DAEMON",
        "move" : 5,
        "wounds" : 5,
        "save" : 5,
        "bravery" : 10,
        "cost" : 5,
        "keywords" : ["CHAOS", "DAEMON"],
        "armykeywords" : ["Khorne", "Tzeentch", "Nurgle", "Slaanesh"],
        "rules" : []
      },
      {
        "name" : "DEATHMAGE",
        "move" : 5,
        "wounds" : 5,
        "save" : 6,
        "bravery" : 7,
        "cost" : 3,
        "keywords" : ["DEATH", "DEATHMAGE"],
        "armykeywords" : ["Grand Host of Nagash", "Legion of Sacrament", "Legion of Blood", "Legion of Night"],
        "rules" : []
      },
      {
        "name" : "DRAGON OGOR",
        "move" : 8,
        "wounds" : 10,
        "save" : 5,
        "bravery" : 7,
        "cost" : 10,
        "keywords" : ["CHAOS", "BEASTS OF CHAOS", "THUNDERSCORN", "DRAGON OGOR"],
        "armykeywords" : [],
        "rules" : []
      },
      {
        "name" : "DUARDIN",
        "move" : 4,
        "wounds" : 5,
        "save" : 4,
        "bravery" : 7,
        "cost" : 4,
        "keywords" : ["ORDER", "DUARDIN"],
        "armykeywords" : ["Cities of Sigmar", "Fyreslayers", "Kharadron Overlords"],
        "rules" : []
      },
      {
        "name" : "GOR",
        "move" : 6,
        "wounds" : 5,
        "save" : 6,
        "bravery" : 6,
        "cost" : 3,
        "keywords" : ["CHAOS", "GOR", "BRAYHERD"],
        "armykeywords" : ["Beasts of Chaos", "Tzeentch"],
        "rules" : []
      },
      {
        "name" : "GROT",
        "move" : 5,
        "wounds" : 4,
        "save" : 6,
        "bravery" : 4,
        "cost" : 3,
        "keywords" : ["DESTRUCTION", "GROT", "GLOOMSPITE GITZ"],
        "armykeywords" : ["Moonclan", "Spiderfang"],
        "rules" : []
      },
      {
        "name" : "HUMAN",
        "move" : 5,
        "wounds" : 5,
        "save" : 5,
        "bravery" : 7,
        "cost" : 4,
        "keywords" : ["ORDER", "HUMAN", "CITIES OF SIGMAR"],
        "armykeywords" : [],
        "rules" : []
      },
      {
        "name" : "IRONJAW ORRUK",
        "move" : 4,
        "wounds" : 6,
        "save" : 5,
        "bravery" : 7,
        "cost" : 5,
        "keywords" : ["DESTRUCTION", "ORRUK", "ORRUK WARCLANS", "IRONJAWS"],
        "armykeywords" : [],
        "rules" : []
      },
      {
        "name" : "MALIGNANT",
        "move" : 6,
        "wounds" : 5,
        "save" : 4,
        "bravery" : 10,
        "cost" : 12,
        "keywords" : ["DEATH", "MALIGNANT", "NIGHTHAUNT"],
        "armykeywords" : [],
        "rules" : ["Fly", "Ethereal"]
      },
      {
        "name" : "MORDANT",
        "move" : 6,
        "wounds" : 6,
        "save" : 5,
        "bravery" : 10,
        "cost" : 6,
        "keywords" : ["DEATH", "MORDANT", "FLESH-EATER COURTS"],
        "armykeywords" : [],
        "rules" : []
      },
      {
        "name" : "MORTAL",
        "move" : 5,
        "wounds" : 5,
        "save" : 5,
        "bravery" : 7,
        "cost" : 4,
        "keywords" : ["CHAOS", "MORTAL"],
        "armykeywords" : ["Khorne", "Tzeentch", "Nurgle", "Slaanesh"],
        "rules" : []
      },
      {
        "name" : "OGOR",
        "move" : 6,
        "wounds" : 7,
        "save" : 5,
        "bravery" : 8,
        "cost" : 7,
        "keywords" : ["DESTRUCTION", "OGOR", "OGOR MAWTRIBES"],
        "armykeywords" : ["Beastclaw Raiders", "Gutbusters"],
        "rules" : []
      },
      {
        "name" : "OSSIARCH BONEREAPER",
        "move" : 5,
        "wounds" : 5,
        "save" : 5,
        "bravery" : 10,
        "cost" : 5,
        "keywords" : ["DEATH", "OSSIARCH BONEREAPERS"],
        "armykeywords" : [],
        "rules" : []
      },
      {
        "name" : "SAURUS",
        "move" : 5,
        "wounds" : 6,
        "save" : 4,
        "bravery" : 8,
        "cost" : 6,
        "keywords" : ["ORDER", "SERAPHON", "SAURUS"],
        "armykeywords" : [],
        "rules" : []
      },
      {
        "name" : "SKAVEN",
        "move" : 6,
        "wounds" : 5,
        "save" : 6,
        "bravery" : 6,
        "cost" : 3,
        "keywords" : ["CHAOS", "SKAVEN", "SKAVENTIDE"],
        "armykeywords" : ["Masterclan", "Clans Pestilens, Nurgle", "Clans Verminus", "Clans Skryre", "Clans Moulder", "Clans Eshin"],
        "rules" : []
      },
      {
        "name" : "SKELETON",
        "move" : 4,
        "wounds" : 5,
        "save" : 6,
        "bravery" : 10,
        "cost" : 3,
        "keywords" : ["DEATH", "SKELETON", "DEATHRATTLE"],
        "armykeywords" : [],
        "rules" : []
      },
      {
        "name" : "SKINK",
        "move" : 8,
        "wounds" : 4,
        "save" : 6,
        "bravery" : 6,
        "cost" : 4,
        "keywords" : ["ORDER", "SERAPHON", "SKINK"],
        "armykeywords" : [],
        "rules" : []
      },
      {
        "name" : "STORMCAST ETERNAL",
        "move" : 5,
        "wounds" : 5,
        "save" : 4,
        "bravery" : 8,
        "cost" : 5,
        "keywords" : ["ORDER", "CELESTIAL", "HUMAN", "STORMCAST ETERNALS"],
        "armykeywords" : [],
        "rules" : []
      },
      {
        "name" : "VAMPIRE",
        "move" : 5,
        "wounds" : 5,
        "save" : 5,
        "bravery" : 10,
        "cost" : 4,
        "keywords" : ["DEATH", "VAMPIRE", "SOULBLIGHT"],
        "armykeywords" : [],
        "rules" : []
      },
      {
        "name" : "SYLVANETH",
        "move" : 5,
        "wounds" : 5,
        "save" : 5,
        "bravery" : 7,
        "cost" : 4,
        "keywords" : ["ORDER", "SYLVANETH"],
        "armykeywords" : [],
        "rules" : []
      },
    ]
